### ISSUE TITLE
Mock router

### ISSUE THREAD

**Issue by jackmellis** [jackmellis/vuenit#21]

**Comment by jackmellis** [comment]
@robodude you briefly mentioned this [here](https://github.com/jpex-js/vue-inject/issues/10) and it's something I've been thinking about adding for a while. Did you have any expectations in mind?

**Comment by robokozo** [comment]
No not really.

My main use case was something like this:

`expect(vm.$router.push).toHaveBeenCalledWith({ name: "destination"});`

Vuenit handles this case perfectly as is with:

```
inject: {
    $router: {
         push: jest.fn()
    }
}
```

I'm still not comfortable with integration testing in the virtual dom, so I'm careful to check if the router works as expected with testcafe (http://devexpress.github.io/testcafe/)

**Comment by jackmellis** [comment]
Yes that's exactly how I have been mocking $router and $route.

What I had in mind was some way to quickly spin up a mock router that already had stubbed methods, i.e. `var {$router, $route} = vuenit.router(); $router.push(); // etc`

That would be extremely easy to do. But I'm wondering if a mock router would want to do more than this, perhaps emit route change events and stuff like that so you can test that the application is navigating to the correct place etc.

**Comment by jackmellis** [comment]
@robodude I haven't done much full blown integration testing. I'm not sure how relevant something like vuenit would be. Would you not be testing your entire application with *real* (or *semi-real*) dependencies, rather than mounting and testing individual components?

**Comment by robokozo** [comment]
Your're right, it wouldn't be relevant. 

When doing the end to end testing, I don't mock/fake anything and just switch the api repository end point urls. 

I brought it up because initially I thought you were considering having vuenit do something special with router-view tags. I can test for that during end to end testing. But on a component level unit test, I wouldn't want to be testing that vue-router works.

**Comment by jackmellis** [comment]
No I wasn't thinking of doing anything with router-view/router-link tags as this I think goes far beyond a simple unit test and into semi-integration territory. My plan is to be able to quickly spin up a `$route` and `$router` object to inject into your component. Potentially they could speak to eachother so you can test that rather than just testing that `$router.push` has been called, you could test that `$route.path` is correct. There are couple of other things that aren't easy to test right now, like component-level navigation guards etc.

I'll probably put together an API checklist at some point.

**Comment by jackmellis** [comment]
Creation:
```js
// creates an empty router, or one with a default route?
let {$router, $route} = vuenit.router();
// creates a router with several routes, somehow determine a default one?
let {$router, $route} = vuenit.router([
  {
    path : '/',
    children : []
  }
]);
// array of strings would be normalised into the above format
let {$router, $route} = vuenit.router(['/', '/users']);
// object configuration similar to vue-router
let {$router, $route} = vuenit.router({
  routes : []
});
```

$route
```js
$route.path // '/users
$route.match // []
$route.query // {}
$route.params // {}
$route.fullPath // '/users/userId?query=x'
$route.activate(); // same as $route.push(myRoute) probably need to pass in params/queries
$route.activate({query : {}, params : {}});
$route.active; // boolean flag ti indicate route is currently active
```

$router
```js
$router.push(); // needs to accept a string and an object
$router.replace();
$router.currentRoute // returns $route
$router.go(n);
$router.back();
$router.forward();
$router.addRoutes([]); // takes same variable syntax as the constructor
$router.routes // returns all routes so you can activate them manually
```

- as we're only interested in testing a specific component, the mock router will ignore any `component` options and will just stay on the current component.  
- when the route changes the component's $route object needs to be changed and trigger any watchers. This may require using `vm.$set` to attach the route as a data property  
- when $route changes, activate navigation guards.
- if the route has `props : true` / `props(){}` somehow we want to pass the route props into the component
- make sure to support deeply nested routes
- https://github.com/pillarjs/path-to-regexp for pattern matching

**Comment by jackmellis** [comment]
route props can also be an object containing static values...
