### ISSUE TITLE
Polyfill for Array.prototype.find required to use vuenit with PhantomJS

### ISSUE THREAD

**Issue by aidangarza** [jackmellis/vuenit#43]
I know this isn't technically an issue with vuenit itself, but in order to use vuenit with the Vue-CLI Webpack template (which uses PhantomJS), a polyfill like [phantomjs-polyfill-find](https://www.npmjs.com/package/phantomjs-polyfill-find) is required.

`lib/router/router.js:137` is the breaking line when mockRouter is used without a polyfill.

Perhaps a note should be added to the ReadMe and/or the docs.

**Comment by jackmellis** [comment]
Yep that's a bug, I've tried to keep vuenit as ES5-safe as possible but this one has slipped through the net
