### ISSUE TITLE
Install option cannot be set as default in component.config

### ISSUE THREAD

**Issue by aidangarza** [jackmellis/vuenit#44]
In `lib/component/index.js`, the "Run install option" block happens before options are merged with defaults; so, an `install` function in `component.config` will never run.

In my current project, I am using a component library (element-ui), and almost all of my components will contain components from this library; so, the ability to `use` this extension by default would be beneficial.

I thought about making a pull request, but wondered if there was a good reason for install not to be included as a default.

**Comment by jackmellis** [comment]
No reason i can think of. I'd definitely consider this a fixable bug! Would it help at all to use shallow rendering instead of using the ui components? Or do you need their functionality for your tests to run?
