### ISSUE TITLE
Injected $router is undefined

### ISSUE THREAD

**Issue by aidangarza** [jackmellis/vuenit#50]
I have a component that looks like this:

    export default {
      props: {
        ...
        to: { ... }
      },
      methods: {
        go () { this.$router.push(this.to) }
      }
    }

And a test that looks like this:

    describe('go()', () => {
      it('should change the current route', () => {
        const { $router, $route } = mockRouter(['/', '/businesses'], '/')
        const vm = shallow(ButtonLink, { inject: { $router, $route }, props: { to: '/businesses' } })
        
          vm.go()

          expect(vm.$route.path).to.eql('/businesses')
        })
      })
    })

When I run this test, I get the following error:

    undefined is not an object (evaluating 'this.$router.push')

For some reason `vm.$router` is undefined, while `$router` is defined in the scope of the test.

**Comment by jackmellis** [comment]
That's very unusual, I haven't come across that myself. Any chance you can replicate the issue in a stand alone repo for me to see? 

If you do `console.log(vm.$router)` in your test does it show as undefined? And the same if you `console.log(this.$router)` within your go method?

I will have a dig around in the meantime

**Comment by aidangarza** [comment]
Both a `console.log(vm.$router)` in the test and a `console.log(this.$router)` in the method print `undefined`.

I'll try to replicate in a minimal demo environment for you.

**Comment by jackmellis** [comment]
I'm definitely not able to replicate this myself! A couple of thoughts:  
- are you setting `config.inject` or `config.router` at some point?  
- any chance somewhere in your test environment you are installing the real vue-router which is somehow messing things up with the mock version?

**Comment by aidangarza** [comment]
I am not using `config.inject` or `config.router` anywhere. I use mockRouters in all applicable tests.

**Comment by aidangarza** [comment]
Steps to recreate:

1. Create a fresh instance of Webpack project from vue-cli with all defaults, except make sure that you say `Y` when it asks to install vue-router -> `vue init webpack`
2. Install vuenit -> `npm install -D vuenit`
3. Add the following to the `Hello.vue` script

        methods: {
          go () {
            this.$router.push('/poodles')
          }
        }

4. Replace `Hello.spec.js` with the following

        import Hello from '@/components/Hello'

        import { shallow, mockRouter } from 'vuenit'

        describe('Hello.vue', () => {
          describe('go()', () => {
            it('should change the route to "/poodles"', () => {
              const { $router, $route } = mockRouter(['/', '/poodles'], '/')
              const vm = shallow(Hello, { inject: { $router, $route } })

              vm.go()

              expect(vm.$route.path).to.eql('/poodles')
            })
          })
        })

5. Run `npm run unit`

You should see this error message:

    Hello.vue
      go()
      01 06 2017 12:32:29.957:WARN [reporter]: SourceMap position not found for trace: undefined
      ✗ should change the route to "/poodles"
	undefined is not an object (evaluating 'this.$router.push')
	go@index.js:12042:19
	boundFn@webpack:///~/vue/dist/vue.esm.js:165:0 <- index.js:409:16
	webpack:///test/unit/specs/Hello.spec.js:11:6 <- index.js:11907:12

**Comment by jackmellis** [comment]
Okay so the issue is that when you start running the tests, karma/webpack loads all files in, including `router/index.js` and the line `Vue.use(Router)` creates an *unenumerable, unconfigurable, unwritable* `$router` property on the Vue prototype. There is then no way to overwrite it with a mocked value.

The easiest way to bypass this is to exclude `router/index.js` from the coverage report. In `test/unit/index.js` change line 12 to:
```js
const srcContext = require.context('../../src', true, /^\.\/(?!(main|router\/index)(\.js)?$)/)
srcContext.keys().forEach(srcContext)
```
If you **do** want to include that file in your coverage, you could wrap it in a function instead:
```js
import Vue from 'vue'
import Router from 'vue-router'
import Hello from '@/components/Hello'

export default function(){
  Vue.use(Router)

  return new Router({
    routes: [
      {
        path: '/',
        name: 'Hello',
        component: Hello
      }
    ]
  })
}

```
and then in main.js:
```js
new Vue({
  el: '#app',
  router : router(),
  template: '<App/>',
  components: { App }
})
```

In the meantime I may see if I can add something to the `vue-inject` library to account for this.

**Comment by jackmellis** [comment]
Could you try reinstalling node_modules from scratch and testing again? Hopefully it should all work nicely.

**Comment by aidangarza** [comment]
That did it! Thank you, sir!

I thought that since `./router` was only imported in `main.js`, and `main.js` was already excluded, that it wouldn't be imported into the test environment. Vuenit is making huge strides in being compatible with the vue-cli templates with this stuff.

<img width="457" alt="screen shot 2017-06-02 at 12 27 00 pm" src="https://cloud.githubusercontent.com/assets/6539867/26737227/da5c7300-478e-11e7-9dfd-7d3ff9242cb7.png">

**Comment by jackmellis** [comment]
Excellent, I'm pleased it's going well.

`require.context` looks for all files (excluding main.js), regardless of whether they're used in your codebase or not, then the next line `require`s each file. I cant help but think this is a risky thing to do as it can have side affects (like this issue) and removes from the atomicity of unit testing. However, this is the only way (apparently) to get full code coverage in this sort of configuration.
