### ISSUE TITLE
Modules don't support actions

### ISSUE THREAD

**Issue by timwis** [jackmellis/vuenit#51]
Hello, I'm trying to mock my store, which consists of 2 modules that contain state and actions. `mockStore` lets me pass state inside the `modules` object, but `actions` don't get properly mapped via `mapActions` unless they're top-level. Any suggestions?

**Comment by jackmellis** [comment]
mockStore is tested with mapActions and nested modules so it should work fine. Do you have a code example? Preferably both the component and the test.

Also what version of Vuex are you using?

**Comment by jackmellis** [comment]
@timwis are you still having this issue?

**Comment by timwis** [comment]
Sorry @jackmellis I haven't had a chance to go back and test it again -- my workaround got the job done. You're welcome to close the issue and when I get a chance to test it again, I'll re-open it with a code sample if it still doesn't work.

**Comment by jackmellis** [comment]
Sure thing. Out of curiosity, what was your workaround?
