### ISSUE TITLE
Can't access $route.name

### ISSUE THREAD

**Issue by keligijus** [jackmellis/vuenit#57]
For some reason, `this.$route.name` is  undefined in a Component that is being tested.

I had to change change my code to `this.$route.matched[0].name` to access the route name.

The component is mounted as per docs (and works ok):

``` javascript
  const { $router } = mockRouter()
  const $store = mockStore(storeOptions)

  const options = {
    inject: { $router, $store },
    stubComponents: true
  }

// <...>

const vm = mount(Component, options)
```

**Comment by jackmellis** [comment]
Thanks, looks like the name property has been missed. I'll get it fixed asap, nobody wants awkward references in their code just to get tests to pass!

**Comment by jackmellis** [comment]
This should be fixed now.

https://github.com/jackmellis/mock-vue-router/releases/tag/0.1.2

**Comment by keligijus** [comment]
Awesome! 👍
