### ISSUE TITLE
[Vue warn]: Property or method "$$typeof" is not defined on the instance but referenced during render

### ISSUE THREAD

**Issue by beliolfa** [jackmellis/vuenit#59]
I get this error in this simple test. No problem if I search for `div`

What I am missing here? Thank you!

```
import test from 'ava';
import { mount } from 'vuenit';
import AnswerBeat from '../src/components/answerBeat/AnswerBeat';

test('it renders a header', (t) => {
  const vm = mount(AnswerBeat);
  t.true(vm.$contains('#test'));
});
```

**Comment by beliolfa** [comment]
Ok. I was looking into the main component div. There is no point to assert that.

**Comment by jackmellis** [comment]
So was `#test` the root element of your component?

**Comment by beliolfa** [comment]
Yep, it was. 

Only playing around with the lib. But it is not a bug in my mind. There is no reason to assert the rendering of root element.

**Comment by jackmellis** [comment]
That was my original thought, if your root element hasn't been rendered then there's something seriously wrong with the component!
