### ISSUE TITLE
Payload on the expect().call is not what I would expect

### ISSUE THREAD

**Issue by pgobbato-blz** [jackmellis/vuenit#60]
Hello!  Firstly thank you for your work, vuenit is awesome.

I am trying to test a writeable computed on my component: 

```
selectedServices: {
  get() {
    return this.$store.getters["landing/filteredByServices"];
  },
  set(newValue) {
    this.$store.dispatch("landing/setSelectedServices", newValue);
  }
}
```

I am attempting this by mocking the store and then doing an expect -> call like so:

`$store.expect("dispatch", "landing/setSelectedRegions", 1).call(payload => { console.log(payload) });`

I would expect `payload` to be `newValue` from our computed `set()` dispatch.  Instead it is the mocked store object.  Is this working as intended? If so, what would be your suggestion to test that the dispatch to `landing/setSelectedServices` was invoked with `newValue` as its payload?

Thanks for your time!

**Comment by pgobbato-blz** [comment]
From looking around your code, it seems this issue might be best posted on your 'mock-vuex' repo.  I can move it there if you prefer!

**Comment by pgobbato-blz** [comment]
From some more looking around your code, it seems I need to set up the .call() like so:

`$store.expect("dispatch", "landing/setSelectedRegions", 1).call((context, payload) => { console.log(payload) });`

You might want to update your docs; this led me astray: https://jackmellis.gitbooks.io/vuenit/content/store/when/call.html

Feel free to close this as you see fit.

**Comment by jackmellis** [comment]
Yes the `call` method takes the same parameters as a real action or mutation would. I should definitely update the docs on this, thanks!

**Comment by jackmellis** [comment]
Thanks for pointing this out, I've updated the docs.

**Comment by pgobbato-blz** [comment]
Awesome, you rock.  Thanks!
