### ISSUE TITLE
Mocking router with children

### ISSUE THREAD

**Issue by pgobbato-blz** [jackmellis/vuenit#66]
Hello Jack,

I've been running around myself in circles trying to use your mockRouter().

I am trying to mock a route that is set up like so:
```
path: "/incident/:issueKey",
component: MainComponent,
props: true,
   children: [
   {
      path: "",
      component: ChildComponent1,
      name: "child1"
   },
   {
      path: "additional",
      component: ChildComponent2,
      name: "child2"
   }
]
```
In a component, I push to it like this:
```
this.$router.push({ name: "child1", params: { issueKey: key } })
```

I've tried setting up a mock route in numerous ways; none of them have a params object populated with `issueKey`.  How would you mock this route?  

Am I right in assuming that I should be able to assert on the mock router like so, given a properly mocked router?
```
expect(mockRouter.$router.currentRoute.params.issueKey).toEqual("123");
```

Thanks in advance for your help.  
-Pietro

**Comment by jackmellis** [comment]
I have tried to replicate this with the below code but as far as I can tell, the params is working correctly.  
Could you let me know if there are any discrepancies between my example and your actual code?  

```js
(async function(){
  require('browser-env')();
  const {mount, mockRouter} = require('vuenit');

  const MainComponent = {
    name : 'MainComponent',
    template : `<div>
      Main Component
      <router-view/>
    </div>`,
    props : ['issueKey'],
    methods : {
      goToChild(key){
        this.$router.push({ name : 'child1', params : { issueKey : key } });
      }
    }
  };

  const ChildComponent1 = {
    name : 'ChildComponent1',
    template : '<div>Child Component 1</div>',
    props : ['issueKey']
  };

  const ChildComponent2 = {
    name : 'ChildComponent2',
    template : '<div>Child Component 2</div>',
    props : ['issueKey']
  };

  const {$router} = mockRouter([
    {
      path : '/incident/:issueKey',
      component : MainComponent,
      props : true,
      children : [
        {
          path : '',
          component : ChildComponent1,
          name : 'child1'
        },
        {
          path : 'additional',
          component : ChildComponent2,
          name : 'child2'
        }
      ]
    }
  ]);

  const vm = mount(MainComponent, { inject : { $router } });

  console.log($router.currentRoute.path); // incident/:issueKey
  console.log($router.currentRoute.params.issueKey); // :issueKey

  vm.goToChild('123');

  console.log($router.currentRoute.path); // incident/123//
  console.log($router.currentRoute.params.issueKey); // 123
  await vm.$nextTick();
  console.log(vm.issueKey); // 123
}())
```

The only other obvious thing is do your components have any route guards that might be preventing the router from moving on? i.e. `beforeRouteEnter` or `beforeRouteLeave` ?

*(I've also noticed a bug where it's picking up the parent route rather than the child one because the child's path is empty, but I don't think that will be affecting this scenario)*

**Comment by pgobbato-blz** [comment]
Thanks for your reply, Jack.

I omitted some important information, apologies: The main difference is that I am pushing to this route from another component not mentioned in the route I posted before; I am testing that component.  It looks something like this, along with some html in a template:

```
export default {
        name: "Search",
        data() {
            return {
                goToIncidentKey: ""
            };
        },
        methods: {
            goToIncident() {
                this.$router.push({ name: "child1", params: { issueKey: this.goToIncidentKey} })
            }
        }
    }
```

Could the bug you mentioned be affecting us here, given this new bit of info?

**Comment by pgobbato-blz** [comment]
In reponse to your question about `beforeRouteEnter` or `beforeRouteLeave`, I am not using those.  I do, however, have this in my router - though I don't think it should impact me:
```
router.beforeEach((to, from, next) => {
   const layout = to.query.layout;
   this.store.dispatch("setLayout", layout);

   next();
});
```

**Comment by pgobbato-blz** [comment]
My test code:
```
            vm = vuenit.component(ComponentUnderTest, options);
            console.log(mockRouter.$router.currentRoute.fullPath); // "/"
            vm.goToIncidentKey = "OPS-123";
            vm.goToIncident();
            console.log(mockRouter.$router.currentRoute.fullPath); // "/incidentPage"
```
This is interesting, because it is routing to the `name` of the path, not the `path` itself `/incident/:issueKey`

**Comment by jackmellis** [comment]
That is interesting because if the mock router fails to find a matching route, it defaults to creating a new route with the provided name. That example would suggest it can't find a route with the provided name...

**Comment by jackmellis** [comment]
Could I see the part of your test that creates the mock router?

**Comment by pgobbato-blz** [comment]
Ok, good to know, that points at an incorrectly mocked router.

Thanks for your help! Yes, here they are:

I've tried several variations (including/excluding components, names, props, etc) of these two:
```        
        vuenit.mockRouter({
            path: "/incident/:issueKey",
            children: [
                {
                    path: "",
                    name: "child1"
                },
                {
                    path: "additional",
                    name: "child2"
                }
            ]
        });
```
and a simpler
```
         vuenit.mockRouter({
            path: "/incident/:issueKey",
            name: "child1"
        });
```
I also tried a copy of your mock from your first repy. 

As I was typing this out, I noticed a difference between your mock and mine, yours is an array of paths, mine is an object.  My understanding was that mockRouter supports either, but that seems to not be the case.  By wrapping them in brackets, I now got it to work.  I'm leaving what I had here for reference in case it is useful.  Here is what does work:
```
        vuenit.mockRouter([{
            path: "/incident/:issueKey",
            children: [
                {
                    path: "",
                    name: "child1"
                },
                {
                    path: "additional",
                    name: "child2"
                }
            ]
        }]);
```
and this works too
```
         vuenit.mockRouter([{
            path: "/incident/:issueKey",
            name: "child1"
        }]);
```

**Comment by pgobbato-blz** [comment]
And upon looking back at your docs, I see I was imagining things, and objects are indeed not supported in the way I was using them. 

Thanks again for the support Jack, sorry for taking up your time. ;)

**Comment by jackmellis** [comment]
Absolutely no problem! Funnily enough when writing the above example I forgot it had to be wrapped in an array and it wouldn't work!
