### ISSUE TITLE
vm.$contains() fails when looking for a root node class

### ISSUE THREAD

**Issue by afontcu** [jackmellis/vuenit#74]
Hi there,

I've been playing with your library for a while and I think there's something weird when trying to assess that a class exists in the root node of a component:

my comp:
```vue
<template>
  <div class="o-media"
    :class="[
      align && `o-media--${align}`,
      size && `o-media--${size}`,
      { 'o-media--reverse': reverse }
    ]">
    ...
</div>
</template>
```

my test:
```js
  it('should render correct nodes', () => {
    let vm = mount(Media, {
      props
    })
    expect(vm.$contains('div.o-media')).toBeTruthy()
  })
```

Tried removing the binding classes, nothing changed.

I'm assuming it has something to do with being the root node, but again it's just an assumption...

Thanks for your time!

**Comment by jackmellis** [comment]
Yes it is to do with it being the root node as $contains/$find etc. start by looking at the root node's children.

To check the above you could write something like:
```js
expect(vm.$el.classList.contains('o-media')).toBeTruthy();
```

However, you are not the first person to be caught out by this and so I think I will change this functionality in the next major release (sometime this week hopefully). So you can make assertions on the root element as well as its children.

**Comment by afontcu** [comment]
Great! This worked for me as well:

```js
vm.$html.includes('o-media')
```

thanks!
