### ISSUE TITLE
Ability to test extended components

### ISSUE THREAD

**Issue by ajm5774** [jackmellis/vuenit#81]
I am testing component 'Transformation' which extends the 'Translation' component.

The code is running fine but I am getting these errors when attempting to mount:

```
'[Vue warn]: The data property "modules" is already declared as a prop. Use prop default value instead.

(found in <Root>)'
'[Vue warn]: The data property "model" is already declared as a prop. Use prop default value instead.

(found in <Root>)'
'[Vue warn]: The data property "aliases" is already declared as a prop. Use prop default value instead.
```

This is what my unit tests look like
```Javascript
import Vue from 'vue';
import { mount } from 'vuenit';
import Transformation from './Transformation.vue';
import Translation from '../Translation/Translation.vue';

const options = {
  Vue: Vue.extend(Translation),
};

fdescribe('Transformation component', () => {
  let model;
  let vm;

  beforeEach(() => {
    model = { id: 3, name: 'name' };
    options.props = { aliases: [], model, modules: [] };

    vm = mount(Transformation, options);
  });

  it('should open the edit modal when edit is clicked', () => {

  });

  it('should emit a remove event when the delete button is clicked', () => {

  });
});
```

Translation has the properties defined, but transformation only defines a few functions that aren't defined in translation. If you need that code as well then I can link it, but it doesn't seem relevant to the problem.

When inspecting the mounted component, the properties are all undefined.

**Comment by ajm5774** [comment]
Turns out that this was caused because of errors during the mount process. Functions were being called using properties on the 'model' object that were undefined. That being said, better error handling could make this easier to work through.

**Comment by jackmellis** [comment]
So am I right in thinking Translation has aliases, model, and module props?

The way vuenit sets props on your component-under-test is to wrap it in a parent component that has the props as data properties. But if the base Vue class already has those props, I can see how this might cause an issue.

I'm wondering whether setting Vue to the Trabslation component is the best way to test this, although I haven't played around with it. What if when you mount transformation, you extend it at that point instead? Something like:
```js
mount(Vue.extend(Translation).extend(Trabsformation));
```
I have no idea whether that will work or not, I'll probably have to have a look into this further.

**Comment by jackmellis** [comment]
On second thoughts I'm not sure whether you can mount a Vue.extend'd component at all right now, that alone might need some development

**Comment by ajm5774** [comment]
Yes, Translation has the aliases, model, and module props

When I try the below code:
```Javascript
mount(Vue.extend(Translation).extend(Transformation), options);
```
I get this:

```
'[Vue warn]: Failed to mount component: template or render function not defined.
```

I think that being able to unit test extended components would be ideal, but I can get away with unit testing the base class and the concrete classes separately for now I think.

**Comment by jackmellis** [comment]
Yes I think currently vuenit assumes the component to be mounted is a plain object (rather than a subclass of Vue), I think this is a big omission so I'll add this issue to the next release.

**Comment by ajm5774** [comment]
```Javascript
mount(Vue.extend(Translation).extend(Transformation), options);
```

This would be the preferred solution for me because I can extend components in the .vue files and don't have to duplicate that logic between component registration and my unit tests. It also makes it easier to chain component extensions.

Right now I have to do something like

```Javascript
// TransformExtension.spec.js
const options = { Vue: Vue.extend(Translation).extend(Transformation) };
const vm = mount(TransformExtension);

// index.js
const translationConstructor = Vue.extend(Translation);
const transformationConstructor = translationConstructor.extend(Transformation)
Vue.component(transformationConstructor.extendOptions.name, transformationConstructor);
Vue.component(transformExtension.name, transformationConstructor.extend(transformExtension));
```

 Ideally all I should have to do is this:
```Javascript
// TransformExtension.spec.js
const vm = mount(TransformExtension);

// index.js
Vue.component(transformation.name, transformation);
Vue.component(transformExtension.name, transformExtension);
```

Note: I will file a request with Vue.js core for the .extendOptions change.

**Comment by jackmellis** [comment]
Forgot to reference the issue in the commit so I'm retro-linking it from here!

https://github.com/jackmellis/vuenit/commit/80e6f26c5cb4c67a7f7d58f0d17fd4fa76cfaa89
