### ISSUE TITLE
Polyfill Object.assign (phantom compatibility)

### ISSUE THREAD

**Issue by ramden** [jackmellis/vuenit#82]
Hello,
I followed the example as described on https://github.com/jackmellis/vuenit

I get :

`TypeError: undefined is not a constructor (evaluating 'Object.assign(Object.create(Parent.$$config || null), options && options.config)')`

Also the line from the example stating:

`import {mount, mockRouter, mockStore} from 'vuenit';`

mockRouter and mockStore are not defined.

Is the example from an old version or is some additional configuration needed? I am using vuenit 1.1.0, vuejs webpack standalone, karma for executing tests

**Comment by jackmellis** [comment]
The docs should all be up to date. Could you post a snippet of the code that's throwing the error? And the full error stack? Are you using phantomjs as your browser?

**Comment by jackmellis** [comment]
If you're using phantom then this could just be because Object.assign (which vuenit uses a *lot*) isn't supported. I think there's a phantomjs object assign polyfill that a lot of people use, but I will also look to make vuenit work around this out of the box. (I've tried to make vuenit phantom-friendly but I think so many people use the pollyfill that this just hasn't been brought up before now)

Let me know if I'm way off track here!

**Comment by ramden** [comment]
Here is a fiddle of the test I am running: https://jsfiddle.net/828axz96/

For the error I get no stack trace, only:

> TypeError: undefined is not a constructor (evaluating 'Object.assign(Object.create(Parent.$$config || null), options && options.config)')
at http://localhost:9876/base/index.js?2c893a3c79c64b626a0e35fb619e3ddf5de87f31:31716

Oh yes, and the Object.assign() ... you mean like with this polyfill? https://www.npmjs.com/package/phantomjs-polyfill-object-assign

What do you use instead of PhantomJS ?

**Comment by ramden** [comment]
Ok. After testing with Chrome Headless it worked. I guess it was the Object.assign(). Maybe this should go into the front page as warning or instruction...

If using PhantomJS use this polyfill ...

Thank you for your help!

**Comment by jackmellis** [comment]
No problem. I will still look to make Vuenit work out of the box with phantom rather than forcing people to use polyfills.
