### ISSUE TITLE
Built-in directives

### ISSUE THREAD

**Issue by Fleeck** [jackmellis/vuenit#85]
Hey, it is not clear how to inject built-in directives into unit test. For example, I have `v-for`, which doesn't even work. Thanks for your work, this package is great :)

**Comment by jackmellis** [comment]
Hi @Fleeck could you perhaps give me an example of this as I'm not sure I understand?

**Comment by Fleeck** [comment]
Sure. I have dynamic `li` and when I try to `$find` them - I get 0 all of the time. Btw, in my `mounted` hook I am assigning to `filteredList`. Should I mock hooks aswell?

```
<li v-for="answer in filteredList" :key="answer.id" class="select__item">
```

**Comment by Fleeck** [comment]
Here is a relevant part of the component.

```
<template>
  <section class="select-one-container">
    <ul class="question-list">
      <li v-for="answer in filteredList" :key="answer.id" class="select__item">
        <span class="select__answer-text" v-html="answer.answerText"></span>
      </li>
    </ul>
  </section>
</template>

<script>
  export default {
    name: 'select-one',
    data: () => ({
      searchable: false,
      selectedAnswer: '',
      searchQuery: '',
      filteredList: []
    }),
    props: {
      answers: { type: Array, required: true },
      subType: { type: Number, default: 0 }
    },
    mounted () {
      this.filteredList = this.answers
    }
  }
</script>
```

**Comment by Fleeck** [comment]
So, mainly there are 2 questions:

1. Should default directive be mocked?
2. Should cmp hooks be mocked?

**Comment by jackmellis** [comment]
No default directives don't need mocking. As for hooks, you should only worry about mocking/stubbing them when they are doing something impure, like making ajax calls or some other side effects.

As far as I can see, doing something like this should work just fine:
```js
vm = vuenit.mount(Component, {
  props: {
    answers: [
      {
        id: 1,
        answerText: 'x'
      }
    ]
  }
});

vm.$find('li').length === 1
```

**Comment by Fleeck** [comment]
Exactly. This is the test case I've got:
```
  it('renders answers correctly', () => {
    const options = {
      inject: { $router, $store },
      props: {
        answers: [
          { id: 1, answerText: 'some text' },
          { id: 2, answerText: 'other text' }
        ]
      }
    }

    const vm = shallow(SelectOne, options)
    const items = vm.$find('li')

    expect(items.length).to.equal(2)
  })
```

Unfortunately, this one is failing with `length === 0`...
Using `mount` doesn't help either.

UPD: `console.log(this.filteredList.length)` shows 2, yet test crashes.

**Comment by jackmellis** [comment]
and if you do `console.log(vm.$html)` ?

**Comment by Fleeck** [comment]
All I've got is
 ` '<section class="select-one-container"><div></div> <!----> <ul class="question-list"></ul></section>'`

And if I add simple `li` - it shows up.

Possible bug with `v-for`?

**Comment by jackmellis** [comment]
This is very strange! What if you `mount` instead of `shallow`?

**Comment by Fleeck** [comment]
If I use `mount` no `li` appears, only component HTML.

UPD: When I try to output `fitleredList` in the template, I get `[]`. However, logging this in the `mounted` hook shows me proper array.

**Comment by Fleeck** [comment]
![image](https://user-images.githubusercontent.com/12518334/31087647-807daef8-a7a6-11e7-9cf2-aff9962d58cf.png)

Repro

**Comment by jackmellis** [comment]
Is it possible that the changes made during the mounted hook aren't shown until the next render cycle. Easiest way to check is to swap mounted with created and see what happens

**Comment by Fleeck** [comment]
@jackmellis it works properly with `created` hook. Thanks!.

**Comment by jackmellis** [comment]
Great! I guess from that the mounted hook must be called *after* the component has been rendered at least once (meaning for a split second your component renders with an empty list).

I suppose if you wanted to keep the mounted hook for some reason, you would just have to use `vue.$nextTick` before making your assertions.

**Comment by Fleeck** [comment]
Thanks for the brief explanation :)

**Comment by Fleeck** [comment]
Oh, @jackmellis. one more thing. I have a test which checks button existence, however it fails and the `btn` is always null. Can you check it and tell me where am I wrong?

```  
it('handles button click', () => {
    const options = {
      inject: { $router, $store },
      stubDirectives: true,
      components: {
        'md-button': `<button id="md-button">x</button>`
      }
    }

    const vm = mount(SelectOne, options)
    const btn = vm.$findOne('#md-button')
    expect(btn).to.be.not.null // actually null
  })
```
Template:
```
    <ul class="question-list">
      <li v-for="answer in filteredList" :key="answer.id" class="select__item">
        <md-button
          :class="{ 'md__button--checked': answer === selectedAnswer }"
          class="md-icon-button md-raised md__button"
          @click="handleChange(answer)">
          <md-icon>done</md-icon>
        </md-button>
        <span class="select__answer-text" v-html="answer.answerText"></span>
      </li>
    </ul>
```
